version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8089:80"  
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  
  php:
    image: php:5-fpm    
    volumes:
      - ./code:/code
 